### ISSUE TITLE
NZTM2000.json Bounding Box calculation not same as explicit definition

### ISSUE THREAD

**Issue by dchirst** [linz/NZTM2000TileMatrixSet#69]
Hi!

I'm in the process of updating [Morecantile](https://github.com/developmentseed/morecantile) to support the TileMatrixSet (TMS) 2.0 specification, specified [here](https://docs.ogc.org/is/17-083r4/17-083r4.html).

Part of the changes is the removal of a required `boundingBox` property. They say that as it can always be calculated by other properties, an explicit definition isn't always required. (Their reasoning can be found [here](https://docs.ogc.org/is/17-083r4/21-066r1.html#_making_boundingbox_optional)). 

However, when I try and calculate the `boundingBox` property based on the other information in the file, I get a mismatch. This was recorded in https://github.com/developmentseed/morecantile/issues/103#issue-1692491933. 

I might be missing a subtle difference between NZTM2000 and other common TMS definitions, that means that the calculation is not being generated accurately. However, I can't seem to find an obvious way to calculate the given boundingbox of (274000.0, 3087000.0, 3327000.0, 7173000.0). How do you calculate this boundingBox, and how do I make this calculation from other properties in the definition? Is this a bug?

Thank you so much in advance!

**Comment by blacha** [comment]
Hi @dchirst 

Thanks for the investigation here, it is on my TODO list to upgrade this repo to the new v2 TMS spec!

This issue explains the weird rendering I see when loading the NZTM2000 TMS debug tiles in QGIS, z0 should be a grid of 2 tiles across 4 tiles down, but only the middle-right 4 (ish) tiles are rendered.

![image](https://user-images.githubusercontent.com/1082761/236065548-9296b386-7378-4704-848a-708d95f46db4.png)

The original NZTM2000 TMS was made well before my time here at LINZ and the people who made it have since left LINZ, so I am unsure if we will ever know "why" this was done.

I believe this is a flaw in the TMS definition, the bounding box should in theory be the bounds of the top level matrix. This TMS is somewhat weird as the bounds of the tile matrix vary across the zoom levels and then are constrained by the `boundingBox`.

We have migrated most of our internal systems to use NZTM2000Quad and have been recommending people to move across to that.

As for your problem, are you able to use the `boundingBox` if it exists? I am very hesitant to modify this tile matrix as it has not be modified in many years and is often copy and pasted into a bunch of systems.

**Comment by dchirst** [comment]
Ahh that's really interesting, thank you for investigating and coming back to me! `boundingBox` is optional, so we could still use it if we wanted, or we could deprecate NZTM2000 in favour of only NZTM2000Quad for the time being.

If you want to use my draft NZTM2000 TMS, you can find it [here](https://github.com/developmentseed/morecantile/blob/eda1f513c8f16339fcad2bebd4f3419fe54063a6/morecantile/data/NZTM2000.json). It has the bug we are talking about, but everything else is (I think) in spec!
